### ISSUE TITLE
raise ValueError('object in serialization dump but ' ValueError: object in serialization dump but object_hook not given.

### ISSUE THREAD

**Issue by SebghatYusuf** [mitsuhiko/phpserialize#33]
I was trying to unserialize below bytes:
`b'a:1:{s:10:"Liberation";a:7:{s:4:"year";s:0:"";s:4:"make";s:0:"";s:5:"model";s:0:"";s:4:"body";s:0:"";s:12:"vehicleClass";s:0:"";s:6:"series";s:0:"";s:11:"all_details";O:8:"stdClass":4:{s:21:"Additional Error Text";s:86:"Invalid character(s): 9:E         , 14:I  
       , 15:O         , 16:Z         , 17:X;";s:10:"Error Code";s:7:"1,7,400";s:10:"Error Text";s:259:"1 - Check Digit (9th position) does not calculate properly; 7 - Manufacturer is not registered with NHTSA for sale or importation in the U.S. for use on U.S roads; Please contact the manufacturer directly for more information; 400 - Invalid Characters Present";s:13:"Suggested VIN";s:17:"2345678W!RTYU!!!!";}}}'`
but I got this error

**Comment by angwa** [comment]
I have this same issue and have not been able to correct it up till now.

**Comment by SebghatYusuf** [comment]
@angwa 
I'm not sure if it's possible for you or not, but try to do the serialization on the PHP side. I haven't received any feedback for this though.

**Comment by angwa** [comment]
Thanks, @SebghatYusuf  I've been able to solve my problem with the package

**Comment by SebghatYusuf** [comment]
@angwa awesome!
